### ISSUE TITLE
不知道如何編譯

### ISSUE THREAD

**Issue by godchadigo** [XMuli/AcrylicWindow#1]
像是QtExamples裡面可以直接運行.pro，然後直接啟動即可，但是這個變成cmake，是直接下cmake CMakeFile.txt編譯嗎，不知道如何啟動@@

**Comment by XMuli** [comment]
MacOS/Linux:
```
make build && cd build
cmake ..
make -j16
```

Windows:
直接使用 QtCreator /CLion 打开 CMakeFile.txt 工程，其余步骤和 Build and Run

**Comment by godchadigo** [comment]
有了，謝謝你
